=== sword-2/byBooks/99-vbvmi/vbvmi.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<!-- Investigate a schema for processing an index for verse by verse ministries international -->

	<!-- An error was observed for xlink attribute if the following import was removed -->

	<xs:import namespace="http://www.w3.org/1999/xlink" schemaLocation="http://www.w3.org/1999/xlink.xsd"/>

	<xs:element name="fileTitle" type="xs:string"/>

	<!-- <xs:element name="media" xmlns:xlink="http://www.w3.org/1999/xlink"> -->
	<xs:element xmlns:xlink="http://www.w3.org/1999/xlink" name="media">
		<xs:complexType mixed="true">
			<xs:sequence> <!-- sequence used to add attribute -->
			<xs:element minOccurs="0" name="title" type="xs:string"/>
			<xs:element minOccurs="0" name="taughtBy" type="xs:string"/>
			<xs:element minOccurs="0" name="date" type="xs:date"/>
			<xs:element minOccurs="0" name="format" type="xs:string"/> <!-- format of media -->
			<xs:element minOccurs="0" name="size" type="xs:integer"/> <!-- filesize of media -->
			<xs:element minOccurs="0" name="bkNo" type="xs:integer"/> <!-- book number -->
			<xs:element minOccurs="0" name="lID" type="xs:string"/> <!-- library codes separated by pipe (|) - Lib Congress | Dewey Decimal -->
			<xs:element minOccurs="0" name="subCode" type="xs:decimal"/> <!--chapter number or topic number -->
		</xs:sequence>
		<xs:attribute xmlns:xlink="http://www.w3.org/1999/xlink" ref="xlink:href"/>  <!-- the namespace was moved up to element media -->
		</xs:complexType>
	</xs:element>

	<!-- This is the main element, which uses teh previous building blocks -->
	<xs:element name="file">
	<xs:complexType>
	<xs:sequence>
		<xs:element minOccurs="1" maxOccurs="1" ref="fileTitle"/>
		<xs:element minOccurs="0" maxOccurs="unbounded" ref="media"/>
	</xs:sequence>
	</xs:complexType>
</xs:element>

</xs:schema>

=== sword-2/byBooks/99-vbvmi/01-latest/01.xml
<file xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///../vbvmi.xsd">
<fileTitle>Latest</fileTitle>

<!--
	Copy to index some materials observed on the net at https://versebyverseministry.org/bible-studies/dashboard
-->


<media xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://versebyverseministry.org/lessons/parable-of-the-mustard-seed">
<title>Parable of the Mustard Seed</title>
<format>video</format>
<lID>na|na</lID>
</media>

<media xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://versebyverseministry.org/lessons/parable-of-the-wheat-and-tares">
<title>Parable of the Wheat and the Tares</title>
<format>video</format>
<lID>na|na</lID>
</media>

<media xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://versebyverseministry.org/lessons/salted-with-fire">
<title>Salted with Fire</title>
<format>video</format>
</media>

<media xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://versebyverseministry.org/lessons/cost-of-discipleship">
<title>Cost of Discipleship</title>
<format>video</format>
</media>

<media xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://versebyverseministry.org/livestream">
<title>Mark 6A- A Prophet without Honor</title>
<format>video</format>
<bkNo>41</bkNo>
</media>

<media xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://media.versebyverseministry.org/uploads/products/1/file/823419e62230db3992922e640636b2be.pdf">
<title>Making Deals With God</title>
<format>book/pdf</format>
</media>

<media xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://versebyverseministry.org/lessons/mark-lesson-1a">
<title>The Gospel of Mark 1A Chapter 1:1-4</title>
<format>video</format>
<bkNo>41</bkNo>
</media>

<media xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://versebyverseministry.org/lessons/mark-lesson-1b">
<title>1B Chapter 1:4-8</title>
<format>video</format>
<bkNo>41</bkNo>
</media>


<media xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://versebyverseministry.org/lessons/mark-lesson-1c">
<title>1C Chapter 1:9-13</title>
<format>video</format>
<bkNo>41</bkNo>
</media>

<media xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://versebyverseministry.org/lessons/mark-lesson-1d">
<title>1D Chapter 1:14-20</title>
<format>video</format>
<bkNo>41</bkNo>
</media>

<media xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://versebyverseministry.org/lessons/mark-lesson-1e">
<title>1E Chapter 1:21-34</title>
<format>video</format>
<bkNo>41</bkNo>
</media>

<media xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://versebyverseministry.org/lessons/mark-lesson-1f">
<title>1F Chapter 1:35-45</title>
<format>video</format>
<bkNo>41</bkNo>
</media>

<media xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://versebyverseministry.org/lessons/mark-lesson-2a">
<title>2A Chapter 2:1-12</title>
<format>video</format>
<bkNo>41</bkNo>
</media>

<media xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://versebyverseministry.org/lessons/mark-lesson-2b">
<title>2B Chapter 2:13-17</title>
<format>video</format>
<bkNo>41</bkNo>
</media>

<media xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://versebyverseministry.org/lessons/mark-lesson-2c">
<title>2C Chapter 2:18-22</title>
<format>video</format>
<bkNo>41</bkNo>
</media>

<media xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://versebyverseministry.org/lessons/mark-lesson-2d">
<title>2D Chapter 2:23-28</title>
<format>video</format>
<bkNo>41</bkNo>
</media>

<media xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://versebyverseministry.org/lessons/mark-lesson-3a">
<title>3A Chapter 3:1-6</title>
<format>video</format>
<bkNo>41</bkNo>
</media>

<media xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://versebyverseministry.org/lessons/mark-lesson-3b">
<title>3B Chapter 3:7-12</title>
<format>video</format>
<bkNo>41</bkNo>
</media>

<media xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://versebyverseministry.org/lessons/mark-lesson-3c">
<title>3C Chapter 3:13-19</title>
<format>video</format>
<bkNo>41</bkNo>
</media>

<media xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://versebyverseministry.org/lessons/mark-lesson-3d">
<title>3D Chapter 3:20-30</title>
<format>video</format>
<bkNo>41</bkNo>
</media>

<media xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://versebyverseministry.org/lessons/mark-lesson-3e">
<title>3E Chapter 3:31-35</title>
<format>video</format>
<bkNo>41</bkNo>
</media>

<media xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://versebyverseministry.org/lessons/mark-lesson-4a">
<title>4A Chapter 4:1-12</title>
<format>video</format>
<bkNo>41</bkNo>
</media>

<media xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://versebyverseministry.org/lessons/mark-lesson-4b">
<title>4B Chapter 4:13-25</title>
<format>video</format>
<bkNo>41</bkNo>
</media>

<media xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://versebyverseministry.org/lessons/mark-lesson-4c">
<title>4C Chapter 4:26-34</title>
<format>video</format>
<bkNo>41</bkNo>
</media>

<media xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://versebyverseministry.org/lessons/mark-lesson-4d">
<title>4D Chapter 4:35-41</title>
<format>video</format>
<bkNo>41</bkNo>
</media>

<media xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://versebyverseministry.org/lessons/mark-lesson-5a">
<title>5A Mark 5:1-20</title>
<format>video</format>
<bkNo>41</bkNo>
</media>

<media xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://versebyverseministry.org/lessons/mark-lesson-5b">
<title>5B Mark 5:21-43</title>
<format>video</format>
<bkNo>41</bkNo>
</media>

<media xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://versebyverseministry.org/lessons/mark-lesson-5c">
<title>5C Chapter 5:35-43</title>
<format>video</format>
<bkNo>41</bkNo>
</media>

<media xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://versebyverseministry.org/lessons/mark-lesson-6a">
<title>6A Chapter 6:1-6</title>
<format>video</format>
<bkNo>41</bkNo>
</media>

<media xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://versebyverseministry.org/lessons/mark-lesson-6b">
<title>6B Chapter 6:7-13</title>
<format>video</format>
<bkNo>41</bkNo>
</media>

<media xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://versebyverseministry.org/lessons/mark-lesson-6c">
<title>6C Chapter 6:14-29</title>
<format>video</format>
<bkNo>41</bkNo>
</media>

<media xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://versebyverseministry.org/lessons/mark-lesson-6d">
<title>6D Chapter 6:30-44</title>
<format>video</format>
<bkNo>41</bkNo>
</media>

<media xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://versebyverseministry.org/lessons/mark-lesson-6e">
<title>6E Chapter 6:45-56</title>
<format>video</format>
<bkNo>41</bkNo>
</media>

<media xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://versebyverseministry.org/lessons/mark-lesson-7a">
<title>7A Chapter 7:1-13</title>
<format>video</format>
<bkNo>41</bkNo>
</media>

<media xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://versebyverseministry.org/lessons/mark-lesson-7b">
<title>7B Chapter 7:14-23</title>
<format>video</format>
<bkNo>41</bkNo>
</media>

<media xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://versebyverseministry.org/lessons/mark-lesson-7c">
<title>7C Chapter 7:24-30</title>
<format>video</format>
<bkNo>41</bkNo>
</media>

<media xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://versebyverseministry.org/lessons/mark-lesson-7d">
<title>7D Chapter 7:31-37</title>
<format>video</format>
<bkNo>41</bkNo>
</media>

<media xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://versebyverseministry.org/lessons/mark-lesson-8a">
<title>8A Chapter 8:1-10</title>
<format>video</format>
<bkNo>41</bkNo>
</media>

<media xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://versebyverseministry.org/lessons/mark-lesson-8b">
<title>8B Chapter 8:11-21</title>
<format>video</format>
<bkNo>41</bkNo>
</media>

<media xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://versebyverseministry.org/lessons/mark-lesson-8c">
<title>8C Chapter 8:22-26</title>
<format>video</format>
<bkNo>41</bkNo>
</media>

<media xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://versebyverseministry.org/lessons/mark-lesson-8d">
<title>8D Chapter 8:27-33</title>
<format>video</format>
<bkNo>41</bkNo>
</media>

<media xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://versebyverseministry.org/lessons/mark-lesson-8e">
<title>8E Chapter 8:34-38</title>
<format>video</format>
<bkNo>41</bkNo>
</media>

<media xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://versebyverseministry.org/lessons/mark-lesson-9a">
<title>9A Chapter 9:1-8</title>
<format>video</format>
<bkNo>41</bkNo>
</media>

<media xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://versebyverseministry.org/lessons/mark-lesson-9b">
<title>9B Chapter 9:9-13</title>
<format>video</format>
<bkNo>41</bkNo>
</media>

<media xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://versebyverseministry.org/lessons/mark-lesson-9c">
<title>9C Chapter 9:14-29</title>
<format>video</format>
<bkNo>41</bkNo>
</media>

<media xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://versebyverseministry.org/lessons/mark-lesson-9d">
<title>9D Chapter 9:30-37</title>
<format>video</format>
<bkNo>41</bkNo>
</media>

<media xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://versebyverseministry.org/lessons/mark-lesson-9e">
<title>9E Chapter 9:38-41</title>
<format>video</format>
<bkNo>41</bkNo>
</media>

<media xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://versebyverseministry.org/lessons/mark-lesson-9f">
